-- Generated by scripts/backfill-instructor-service-zones.mjs from public/instructors.kml.
-- 3 polygon rows. Review before applying. Idempotent.
-- Source KML changed for these instructors; rows are overwritten on purpose.
INSERT INTO public.instructor_service_zones(instructor_id,kind,coordinates,raw_name,description) VALUES
('54232c1e-f565-428d-9d88-42088fe47f6f','polygon','[{"lat":13.0375989,"lng":77.6155899},{"lat":13.0397359,"lng":77.6146342},{"lat":13.042105,"lng":77.613097},{"lat":13.0413532,"lng":77.6095794},{"lat":13.0416247,"lng":77.6030134},{"lat":13.0495888,"lng":77.5964474},{"lat":13.0403834,"lng":77.5959375},{"lat":13.0361535,"lng":77.58731},{"lat":13.0338272,"lng":77.5816417},{"lat":13.0260946,"lng":77.5777308},{"lat":13.0135668,"lng":77.5880004},{"lat":13.0074006,"lng":77.5955663},{"lat":13.0139259,"lng":77.6035281},{"lat":13.0194443,"lng":77.6097082},{"lat":13.0335196,"lng":77.6180926},{"lat":13.0375989,"lng":77.6155899}]'::jsonb,'Salauddin','Timings: 6AM to 11AM
Vehicle: Hyundai getz, KAO4MC5896
Service Area: Hebbal
Languages: English Hindi kannada urdu'),
('b0f53106-1f87-444f-9e9e-bcdf7c864076','polygon','[{"lat":12.9878702,"lng":77.6503701},{"lat":12.985891,"lng":77.652059},{"lat":12.9797295,"lng":77.6541328},{"lat":12.9744881,"lng":77.6569792},{"lat":12.9673171,"lng":77.6619538},{"lat":12.9666698,"lng":77.6697174},{"lat":12.9663402,"lng":77.6746537},{"lat":12.9678089,"lng":77.6830662},{"lat":12.9723724,"lng":77.6874016},{"lat":12.9776466,"lng":77.6880464},{"lat":12.9798311,"lng":77.6923397},{"lat":12.9810487,"lng":77.693242},{"lat":12.9817647,"lng":77.6924278},{"lat":12.9859158,"lng":77.6900443},{"lat":12.9912993,"lng":77.686677},{"lat":12.9959624,"lng":77.6834453},{"lat":12.9998299,"lng":77.6811838},{"lat":13.000917,"lng":77.6762055},{"lat":12.9984081,"lng":77.668309},{"lat":12.9923349,"lng":77.6599774},{"lat":12.9905465,"lng":77.6526446},{"lat":12.9884556,"lng":77.6501126},{"lat":12.9878702,"lng":77.6503701}]'::jsonb,'Ameen / Arokia','Timings: 
Ameen Sir: 6 AM - 10 AM

Vehicle: Hyundai i10, Ka04nf9865
Service area: C V Raman Nagar
Languages: English, Hindi, Kannada'),
('05bde5a4-9be7-4b7a-97a3-03903627ab29','polygon','[{"lat":13.0879414,"lng":77.5940458},{"lat":13.0877062,"lng":77.597804},{"lat":13.0929492,"lng":77.6035965},{"lat":13.1027134,"lng":77.6099044},{"lat":13.1070601,"lng":77.6114684},{"lat":13.1127441,"lng":77.6119166},{"lat":13.1185806,"lng":77.6138552},{"lat":13.124253,"lng":77.6106544},{"lat":13.1267491,"lng":77.6050503},{"lat":13.127799,"lng":77.5909197},{"lat":13.1239171,"lng":77.5798789},{"lat":13.1203638,"lng":77.5756319},{"lat":13.1159746,"lng":77.5727583},{"lat":13.1079365,"lng":77.5689653},{"lat":13.1039399,"lng":77.5679193},{"lat":13.0982713,"lng":77.5673024},{"lat":13.0929531,"lng":77.5707325},{"lat":13.090728,"lng":77.5755358},{"lat":13.0879576,"lng":77.5862726},{"lat":13.0879414,"lng":77.5940458}]'::jsonb,'Narasimhareddy','6:00AM to 10:00 AM
Wagon R 2002
hindi, kannada,tamil,telagu and english (manageable)')
ON CONFLICT (instructor_id) DO UPDATE SET coordinates=EXCLUDED.coordinates, kind=EXCLUDED.kind, raw_name=EXCLUDED.raw_name, description=EXCLUDED.description, updated_at=now();
